---
- name: install ssh config
  become: yes
  copy: >
    dest=/etc/ssh/{{ item }}
    force=true
    src={{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - ssh_config
    - sshd_config
  notify: restart ssh

- name: create safe ssh keys
  become: yes
  script: ssh-keys.sh creates=/etc/ssh/ansible_was_here
  notify: restart ssh
